import azure.functions as func
import logging
import json
import os
from openai import AzureOpenAI

# Initialize the Azure Functions App
app = func.FunctionApp(http_auth_level=func.AuthLevel.ANONYMOUS)

# Initialize the Azure OpenAI Client using your local.settings.json variables
# (This reuses the connection across function invocations for better performance)
openai_client = AzureOpenAI(
    azure_endpoint=os.environ.get("AZURE_OPENAI_ENDPOINT"),
    api_key=os.environ.get("AZURE_OPENAI_KEY"),
    api_version="2024-02-01" # Standard production-ready API version
)
model_deployment = os.environ.get("AZURE_OPENAI_DEPLOYMENT", "gpt-5.4-mini-wedding")

@app.route(route="ask-assistant", methods=["POST"])
def ask_assistant(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Processing a live guest question with Azure OpenAI.')

    try:
        # 1. Parse the incoming request payload
        req_body = req.get_json()
        guest_question = req_body.get('question')
        
        if not guest_question:
            return func.HttpResponse(
                json.dumps({"error": "Please provide a 'question' in the request body."}),
                status_code=400,
                mimetype="application/json"
            )
        
        # 2. Call your live deployed Azure OpenAI model
        logging.info(f"Sending question to Azure OpenAI deployment: {model_deployment}")
        
        response = openai_client.chat.completions.create(
            model=model_deployment,
            messages=[
                {
                    "role": "system", 
                    "content": "You are a helpful, enthusiastic AI wedding assistant. Answer questions nicely. Note: Right now, we haven't connected our knowledge base documents yet, so politely tell the guest that specific schedule or location details are coming soon if they ask for exact specifics!"
                },
                {"role": "user", "content": guest_question}
            ],
            temperature=0.7,
            max_completion_tokens=200
        )

        # 3. Extract the text response generated by the model
        ai_reply = response.choices[0].message.content

        return func.HttpResponse(
            json.dumps({"reply": ai_reply}),
            status_code=200,
            mimetype="application/json"
        )

    except Exception as e:
        logging.error(f"Error communicating with Azure OpenAI: {str(e)}")
        return func.HttpResponse(
            json.dumps({"error": "Failed to generate a response from the AI backend."}),
            status_code=500,
            mimetype="application/json"
        )
